### ISSUE TITLE
Modifying dseries does not work as expected

### ISSUE THREAD

**Issue by houtanb** [DynareTeam/dseries#37]
```
zero = dseries(zeros(8,1), '2011q1');

% Modifying all of b (this works)
a = dseries((1:8)', '2011q1');
b = a;
b = b + 1;
assert(~all(a - b == zero));

% Modifying only part of b (this does not work as it modifies a as well)
a = dseries((1:8)', '2011q1');
b = a;
b(dates('2012q2'):dates('2012q4')) = b(dates('2012q2'):dates('2012q4')) + 1;
assert(~all(a - b == zero), 'a and b should not be equal here');
```

**Comment by stepan-a** [comment]
For me this is not a bug... Or the bug is not where you think.  In the second example, if you replace `a=b` by `a = copy(b)` it works flawlessly as expected. With the new OOP interface the statement `b = a` creates a pointer to object `a`. So a modification of `b` changes `a` unless you do a copy (instantiating a new object). This is done automatically for a large number of methods, such as the binary `plus` method, and this is why it works as you expect in the first example. We may decide that we do not wish to do that automatically (so that the two examples would behave consistently), but this is another issue...
